rvm: 2.2
sudo: required
services: docker
env:
  matrix:
  - INSTANCE=default-ubuntu-1204
before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.8.0
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER
script: travis_retry chef exec bundle exec rake integration:docker[${INSTANCE}]
